# Version: 20190203
ARG DOCKER_NOTEBOOK_IMAGE
FROM $DOCKER_NOTEBOOK_IMAGE
ARG JUPYTERHUB_VERSION
ARG JUPYTERLAB_VERSION
ARG NOTEBOOK_VERSION
ARG NB_USER_PASS
ARG GITHUB_ACCESS_TOKEN
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG LOGO_IMAGE

LABEL maintainer='herman.tolentino@gmail.com'

RUN \
    conda config --show-sources
    #mv /opt/conda/conda-meta/pinned /opt/conda/conda-meta/pinned.bak

RUN \
    conda update 'conda' && \
    conda install -c conda-forge -y 'conda=4.7.10' 'conda-build=3.18*' && \
    conda config --prepend channels conda-forge && \
    #conda config --set channel_priority strict && \
    conda config --describe channel_priority && \
    conda config --set ssl_verify no && \
    conda update \
      'openssl' \
      'ca-certificates' \
      'certifi' && \
    conda config --set ssl_verify yes && \
    cat .condarc && \
    python3 -m pip install --no-cache-dir --upgrade pip

USER root

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /home/jovyan/work

RUN \
    # uncomment the line below if necessary
    #/bin/bash upgrade-distro.sh
    ln -sf /bin/bash /bin/sh && \
    ln -s /bin/tar /bin/gtar && \
    echo "jovyan ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Code below based on https://github.com/jenkinsci/docker/issues/543
# For addressing errors: "E: Unable to fetch some archives", "Hash Sum mismatch"
COPY 99fixbadproxy /etc/apt/apt.conf.d/

RUN \
    conda install -c conda-forge --yes \
      "jupyterhub=$JUPYTERHUB_VERSION" \
      "jupyterlab=$JUPYTERLAB_VERSION" \
      'jupyter_client' \
      'jupyter_console' \
      "notebook=$NOTEBOOK_VERSION" \
      'libsodium' && \
      conda clean --all -f -y
RUN \
    jupyter serverextension enable --py jupyterlab --sys-prefix && \
    conda build purge-all && \
    mkdir -p /etc/apt/apt.conf.d/ && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      software-properties-common apt-utils ffmpeg \
      libssl1.0.0 libssl-dev \
      zip unzip file fonts-dejavu tzdata nano && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt-get update && \
    ln -sf /usr/share/zoneinfo/EST /etc/localtime && \
    export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    chmod -R a+w /opt/conda/ && \
    chown -R root:users /opt/conda && \
    chmod g+s /opt/conda && \
    chown -R 1000:1000 /home/jovyan/.conda/
